app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.17.0.2:3306/musicrental
      password: 'password'
      pool-size: 30
      username: root

server:
  error:
    include-binding-errors: always
    include-message: always
